var pokedex = {
    bulbasaur: {
        name: "Bulbasaur",
        type: ["grass", "poison"],
        level: 20,
        pokedexNumber: 001,
        HP: 45,
        attack: 49,
        defence: 49,
        special: 65,
        speed: 45,
        moves: [moves.tackle, 
                moves.razorleaf, 
                moves.vinewhip, 
                moves.absorb]
    },
    ivysaur: {
        name: "Ivysaur",
        type: ["grass", "poison"],
        level: 20,
        pokedexNumber: 002,
        HP: 60,
        attack: 62,
        defence: 63,
        special: 80,
        speed: 60,
        moves: [moves.tackle, 
                moves.razorleaf, 
                moves.vinewhip, 
                moves.gigadrain]
        
    },
    venusaur: {
        name: "Venusaur",
        type: ["grass", "poison"],
        level: 20,
        pokedexNumber: 003,
        HP: 80,
        attack: 82,
        defence: 83,
        special: 100,
        speed: 80,
        moves: [moves.razorleaf, 
                moves.vinewhip, 
                moves.gigadrain, 
                moves.solarbeam]
        
    },
    charmander: {
        name: "Charmander",
        type: ["fire"],
        level: 20,
        pokedexNumber: 004,
        HP: 39,
        attack: 52,
        defence: 43,
        special: 55,
        speed: 65,
        moves: [moves.tackle, 
                moves.scratch, 
                moves.ember, 
                moves.quickattack]
    },
    charmeleon: {
        name: "Charmeleon",
        type: ["fire"],
        level: 20,
        pokedexNumber: 005,
        HP: 58,
        attack: 64,
        defence: 58,
        special: 72,
        speed: 80,
        moves: [moves.flamethrower, 
                moves.scratch, 
                moves.ember, 
                moves.quickattack] 
    },
    charizard: {
        name: "Charizard",
        type: ["fire", "flying"],
        level: 20,
        pokedexNumber: 006,
        HP: 78,
        attack: 84,
        defence: 78,
        special: 109,
        speed: 100,
        moves: [moves.flamethrower, 
                moves.scratch, 
                moves.fly, 
                moves.fireblast]
        
    },
    squirtle: {
        name: "Squirtle",
        type: ["water"],
        level: 20,
        pokedexNumber: 007,
        HP: 44,
        attack: 48,
        defence: 65,
        special: 60,
        speed: 43,
        moves: [moves.tackle, 
                moves.watergun, 
                moves.bubblebeam, 
                moves.bubble]
    },
    wartortle: {
        name: "Wartortle",
        type: ["water"],
        level: 20,
        pokedexNumber: 008,
        HP: 59,
        attack: 63,
        defence: 80,
        special: 72.5,
        speed: 58,
        moves: [moves.tackle, 
                moves.watergun, 
                moves.bubblebeam, 
                moves.surf]
    },
     blastoise: {
        name: "Blastoise",
        type1: ["water"],
        level: 20,
        pokedexNumber: 009,
        HP: 79,
        attack: 83,
        defence: 100,
        special: 95,
        speed: 78,
        moves: [moves.hydropump, 
                moves.strength, 
                moves.bubblebeam, 
                moves.surf]
    },
    caterpie: {
        name: "Caterpie",
        type: ["bug"],
        level: 20,
        pokedexNumber: 010,
        HP: 45,
        attack: 30,
        defence: 35,
        special: 20,
        speed: 20,
        moves: [moves.tackle, 
                moves.stringshot, 
                moves.tackle, 
                moves.stringshot]
    },
    metapod: {
        name: "Metapod",
        type: ["bug"],
        level: 20,
        pokedexNumber: 011,
        HP: 50,
        attack: 20,
        defence: 55,
        special: 25,
        speed: 30,
        moves: [moves.harden, 
                moves.harden, 
                moves.harden, 
                moves.harden]
    },
     butterfree: {
        name: "Butterfree",
        type: ["bug", "flying"],
        level: 20,
        pokedexNumber: 012,
        HP: 60,
        attack: 45,
        defence: 50,
        special: 85,
        speed: 70,
        moves: [moves.gust, 
                moves.psybeam, 
                moves.confusion, 
                moves.poisonpowder]
    },
    weedle: {
        name: "Weedle",
        type: ["bug", "poison"],
        level: 20,
        pokedexNumber: 013,
        HP: 40,
        attack: 35,
        defence: 30,
        special: 20,
        speed: 50,
        moves: [moves.poisonsting, 
                moves.stringshot, 
                moves.tackle, 
                moves.poisonsting]
    },
    kakuna: {
        name: "Kakuna",
        type: ["bug", "posion"],
        level: 20,
        pokedexNumber: 014,
        HP: 45,
        attack: 25,
        defence: 50,
        special: 25,
        speed: 35,
        moves: [moves.harden, 
                moves.harden, 
                moves.harden, 
                moves.harden]
    },
    beedrill: {
        name: "Beedrill",
        type: ["bug", "poison"],
        level: 20,
        pokedexNumber: 015,
        HP: 65,
        attack: 80,
        defence: 40,
        special: 55,
        speed: 75,
        moves: [moves.furyattack, 
                moves.pursuit, 
                moves.pinmissile, 
                moves.twineedle]
    },
    pidgey: {
        name: "Pidgey",
        type: ["normal", "flying"],
        level: 20,
        pokedexNumber: 016,
        HP: 40,
        attack: 45,
        defence: 40,
        special: 35,
        speed: 56,
        moves: [moves.tackle, 
                moves.quickattack, 
                moves.sandattack, 
                moves.peck]
    },
    pidgeotto: {
        name: "Pidgeotto",
        type: ["normal", "flying"],
        level: 20,
        pokedexNumber: 017,
        HP: 63,
        attack: 60,
        defence: 55,
        special: 50,
        speed: 71,
        moves: [moves.wingattack, 
                moves.gust, 
                moves.sandattack, 
                moves.quickattack]
    },
    pidgeot: {
        name: "Pidgeot",
        type: ["normal", "flying"],
        level: 20,
        pokedexNumber: 018,
        HP: 83,
        attack: 80,
        defence: 75,
        special: 70,
        speed: 91,
        moves: [moves.wingattack, 
                moves.gust, 
                moves.fly, 
                moves.quickattack]
    },
    rattata: {
        name: "Rattata",
        type1: "normal",
        level: 20,
        pokedexNumber: 019,
        HP: 30,
        attack: 56,
        defence: 35,
        special: 30,
        speed: 72,
        moves: [moves.tackle, 
                moves.superfang, 
                moves.hyperfang, 
                moves.quickattack]
    },
    raticate: {
        name: "Raticate",
        type1: "normal",
        level: 20,
        pokedexNumber: 020,
        HP: 55,
        attack: 81,
        defence: 60,
        special: 60,
        speed: 97,
        moves: [moves.tackle, 
                moves.superfang, 
                moves.hyperfang, 
                moves.quickattack]
    },
    spearow: {
        name: "Spearow",
        type: ["normal", "flying"],
        level: 20,
        pokedexNumber: 021,
        HP: 40,
        attack: 60,
        defence: 30,
        special: 31,
        speed: 70,
        moves: [moves.sandattack, 
                moves.gust, 
                moves.peck, 
                moves.quickattack]
    },
    fearow: {
        name: "Spearow",
        type: ["normal", "flying"],
        level: 20,
        pokedexNumber: 022,
        HP: 65,
        attack: 90,
        defence: 65,
        special: 61,
        speed: 100,
        moves: [moves.furyattack, 
                moves.gust, 
                moves.fly, 
                moves.quickattack]
    },
    ekans: {
        name: "Ekans",
        type: ["poison"],
        level: 20,
        pokedexNumber: 023,
        HP: 35,
        attack: 60,
        defence: 44,
        special: 47,
        speed: 55,
        moves: [moves.wrap, 
                moves.poisonsting, 
                moves.bite, 
                moves.acid]
    },
    arbok: {
        name: "Arbok",
        type: ["poison"],
        level: 20,
        pokedexNumber: 024,
        HP: 60,
        attack: 85,
        defence: 69,
        special: 72,
        speed: 80,
        moves: [moves.wrap, 
                moves.poisonsting, 
                moves.bite, 
                moves.acid]
    },
    pikachu: {
        name: "Pikachu",
        type: ["electric"],
        level: 20,
        pokedexNumber: 025,
        HP: 35,
        attack: 55,
        defence: 30,
        special: 45,
        speed: 90,
        moves: [moves.tackle, 
                moves.thunderbolt, 
                moves.thunder, 
                moves.quickattack]
    },
     raichu: {
        name: "Raichu",
        type: ["electric"],
        level: 20, 
        pokedexNumber: 026,
        HP: 60,
        attack: 90,
        defence: 55,
        special: 85,
        speed: 100,
        moves: [moves.tackle, 
                moves.thunderbolt, 
                moves.thunder, 
                moves.quickattack]
    },
    sandshrew: {
        name: "Sandshrew",
        type: ["ground"],
        level: 20,
        pokedexNumber: 027,
        HP: 50,
        attack: 75,
        defence: 85,
        special: 25,
        speed: 40,
        moves: [moves.sandattack, 
                moves.slash, 
                moves.dig, 
                moves.scratch]
    },
    sandslash: {
        name: "Sandslash",
        type: ["ground"],
        level: 20,
        pokedexNumber: 028,
        HP: 75,
        attack: 100,
        defence: 110,
        special: 50,
        speed: 65,
        moves: [moves.sandattack, 
                moves.dig, 
                moves.slash, 
                moves.earthquake]
    },
    nidoranF: {
        name: "Nidoran♀",
        type: ["poison"],
        level: 20,
        pokedexNumber: 029,
        HP: 55,
        attack: 47,
        defence: 52,
        special: 40,
        speed: 41,
        moves: [moves.poisonsting, 
                moves.peck, 
                moves.tackle, 
                moves.sandattack]
    },
    nidorina: {
        name: "Nidorina",
        type: ["poison"],
        level: 20,
        pokedexNumber: 030,
        HP: 70,
        attack: 62,
        defence: 67,
        special: 55,
        speed: 56,
        moves: [moves.poisonsting, 
                moves.doublekick, 
                moves.bite, 
                moves.scratch]
    },
    nidoqueen: {
        name: "Nidoqueen",
        type: ["poison", "ground"],
        level: 20,
        pokedexNumber: 031,
        HP: 90,
        attack: 82,
        defence: 87,
        special: 80,
        speed: 76,
        moves: [moves.earthquake, 
                moves.strength, 
                moves.doublekick, 
                moves.bite]
    },
    nidoranM: {
        name: "Nidoran♂",
        type: ["poison"],
        level: 20,
        pokedexNumber: 032,
        HP: 46,
        attack: 57,
        defence: 40,
        special: 40,
        speed: 50,
        moves: [moves.poisonsting, 
                moves.peck, 
                moves.tackle, 
                moves.sandattack]
    },
    nidorino: {
        name: "Nidorino",
        type: ["poison"],
        level: 20,
        pokedexNumber: 033,
        HP: 61,
        attack: 72,
        defence: 57,
        special: 55,
        speed: 65,
        moves: [moves.poisonsting, 
                moves.doublekick, 
                moves.bite, 
                moves.furyattack]
    },
    nidoking: {
        name: "Nidoking",
        type: ["poison", "ground"],
        level: 20,
        pokedexNumber: 034,
        HP: 81,
        attack: 92,
        defence: 77,
        special: 80,
        speed: 85,
        moves: [moves.earthquake, 
                moves.strength, 
                moves.doublekick, 
                moves.bite]
    },
    clefairy: {
        name: "Clefairy",
        type: ["normal"],
        level: 20,
        pokedexNumber: 035,
        HP: 70,
        attack: 45,
        defence: 48,
        special: 60,
        speed: 35,
        moves: [moves.pound, 
                moves.doubleslap, 
                moves.metronome, 
                moves.growl]
    },
    clefable: {
        name: "Clefable",
        type: ["normal"],
        level: 20,
        pokedexNumber: 036,
        HP: 95,
        attack: 70,
        defence: 73,
        special: 85,
        speed: 60,
        moves: [moves.strength, 
                moves.doubleslap, 
                moves.metronome, 
                moves.growl]
    },
    vulpix: {
        name: "Vulpix",
        type: ["fire"],
        level: 20,
        pokedexNumber: 037,
        HP: 38,
        attack: 41,
        defence: 40,
        special: 55,
        speed: 65,
        moves: [moves.ember, 
                moves.quickattack, 
                moves.tackle, 
                moves.flamethrower]
    },
    ninetales: {
        name: "Ninetales",
        type: ["fire"],
        level: 20,
        pokedexNumber: 038,
        HP: 73,
        attack: 76,
        defence: 75,
        special: 90,
        speed: 100,
        moves: [moves.fireblast, 
                moves.quickattack, 
                moves.tackle, 
                moves.flamethrower]
    },
    jigglypuff: {
        name: "Jigglypuff",
        type: ["normal"],
        level: 20,
        pokedexNumber: 039,
        HP: 115,
        attack: 45,
        defence: 20,
        special: 35,
        speed: 20,
        moves: [moves.pound, 
                moves.sing, 
                moves.bodyslam, 
                moves.doubleslap]
    },
    wigglytuff: {
        name: "Wigglytuff",
        type: ["normal"],
        level: 20,
        pokedexNumber: 040,
        HP: 140,
        attack: 70,
        defence: 45,
        special: 65,
        speed: 45,
        moves: [moves.pound, 
                moves.sing, 
                moves.bodyslam, 
                moves.doubleslap]
    },
    zubat: {
        name: "Zubat",
        type: ["poison", "flying"],
        level: 20,
        pokedexNumber: 041,
        HP: 40,
        attack: 45,
        defence: 35,
        special: 35,
        speed: 55,
        moves: [moves.bite, 
                moves.leechlife, 
                moves.supersonic, 
                moves.confuseray]
    },
    golbat: {
        name: "Golbat",
        type: ["poison", "flying"],
        level: 20,
        pokedexNumber: 042,
        HP: 75,
        attack: 80,
        defence: 70,
        special: 70,
        speed: 90,
        moves: [moves.wingattack, 
                moves.leechlife, 
                moves.supersonic, 
                moves.confuseray]
    },
    oddish: {
        name: "Oddish",
        type: ["grass", "poison"],
        level: 20,
        pokedexNumber: 043,
        HP: 45,
        attack: 50,
        defence: 55,
        special: 70,
        speed: 30,
        moves: [moves.absorb, 
                moves.poisonpowder, 
                moves.acid, 
                moves.sleeppowder]
    },
    gloom: {
        name: "Gloom",
        type: ["grass", "poison"],
        level: 20,
        pokedexNumber: 044,
        HP: 60,
        attack: 65,
        defence: 70,
        special: 80,
        speed: 40,
        moves: [moves.absorb, 
                moves.poisonpowder, 
                moves.acid, 
                moves.gigadrain]
    },
    vileplume: {
        name: "Vileplume",
        type: ["grass", "poison"],
        level: 20,
        pokedexNumber: 045,
        HP: 75,
        attack: 80,
        defence: 85,
        special: 95,
        speed: 50,
        moves: [moves.solarbeam, 
                moves.poisonpowder, 
                moves.acid, 
                moves.gigadrain]
    },
    paras: {
        name: "Paras",
        type: ["bug", "grass"],
        level: 20,
        pokedexNumber: 046,
        HP: 35,
        attack: 70,
        defence: 55,
        special: 50,
        speed: 25,
        moves: [moves.scratch, 
                moves.absorb, 
                moves.slash, 
                moves.poisonpowder]
    },
    parasect: {
        name: "Parasect",
        type: ["bug", "grass"],
        level: 20,
        pokedexNumber: 047,
        HP: 60,
        attack: 95,
        defence: 80,
        special: 70,
        speed: 30,
        moves: [moves.scratch, 
                moves.absorb, 
                moves.slash, 
                moves.gigadrain]
    },
    venonat: {
        name: "Venonat",
        type: ["bug", "poison"],
        level: 20,
        pokedexNumber: 048,
        HP: 60,
        attack: 55,
        defence: 50,
        special: 45,
        speed: 45,
        moves: [moves.tackle, 
                moves.confusion, 
                moves.poisonpowder, 
                moves.supersonic]
    },
    venomoth: {
        name: "Venomoth",
        type: ["bug", "poison"],
        level: 20,
        pokedexNumber: 049,
        HP: 70,
        attack: 65,
        defence: 60,
        special: 85,
        speed: 90,
        moves: [moves.gust, 
                moves.confusion, 
                moves.poisonpowder, 
                moves.psybeam]
    },
    diglett: {
        name: "Diglett",
        type: ["ground"],
        level: 20,
        pokedexNumber: 050,
        HP: 10,
        attack: 55,
        defence: 25,
        special: 40,
        speed: 95,
        moves: [moves.sandattack, 
                moves.dig, 
                moves.scratch, 
                moves.growl]
    },
    dugtrio: {
        name: "Dugtrio",
        type: ["ground"],
        level: 20,
        pokedexNumber: 051,
        HP: 35,
        attack: 80,
        defence: 50,
        special: 60,
        speed: 120,
        moves: [moves.earthquake, 
                moves.dig, 
                moves.scratch, 
                moves.growl]
    },
    meowth: {
        name: "Meowth",
        type: ["normal"],
        level: 20,
        pokedexNumber: 052,
        HP: 40,
        attack: 45,
        defence: 35,
        special: 40,
        speed: 90,
        moves: [moves.scratch, 
                moves.bite, 
                moves.payday, 
                moves.tackle]
    },
    persian: {
        name: "Persian",
        type: ["normal"],
        level: 20,
        pokedexNumber: 053,
        HP: 65,
        attack: 70,
        defence: 60,
        special: 65,
        speed: 115,
        moves: [moves.slash, 
                moves.bite, 
                moves.payday, 
                moves.swift]
    },
    psyduck: {
        name: "Psyduck",
        type: ["water"],
        level: 20,
        pokedexNumber: 054,
        HP: 50,
        attack: 52,
        defence: 48,
        special: 60,
        speed: 55,
        moves: [moves.watergun, 
                moves.confusion, 
                moves.scratch, 
                moves.tailwhip]
    },
    golduck: {
        name: "Golduck",
        type: ["water"],
        level: 20,
        pokedexNumber: 055,
        HP: 80,
        attack: 82,
        defence: 78,
        special: 90,
        speed: 85,
        moves: [moves.watergun, 
                moves.confusion, 
                moves.scratch, 
                moves.hydropump]
    },
    mankey: {
        name: "Mankey",
        type: ["fighting"],
        level: 20,
        pokedexNumber: 056,
        HP: 40,
        attack: 80,
        defence: 35,
        special: 40,
        speed: 70,
        moves: [moves.lowkick, 
                moves.karatechop, 
                moves.scratch, 
                moves.leer]
    },
    primeApe: {
        name: "primeApe",
        type: ["fighting"],
        level: 20,
        pokedexNumber: 057,
        HP: 65,
        attack: 105,
        defence: 60,
        special: 65,
        speed: 95,
        moves: [moves.lowkick, 
                moves.karatechop, 
                moves.scratch, 
                moves.crosschop]
    },
    growlithe: {
        name: "Growlithe",
        type: ["fire"],
        level: 20,
        pokedexNumber: 058,
        HP: 55,
        attack: 70,
        defence: 45,
        special: 70,
        speed: 60,
        moves: [moves.ember, 
                moves.bite, 
                moves.flamewheel, 
                moves.leer] 
    },
    arcanine: {
        name: "Arcanine",
        type: ["fire"],
        level: 20,
        pokedexNumber: 059,
        HP: 90,
        attack: 110,
        defence: 80,
        special: 100,
        speed: 95,
        moves: [moves.flamethrower, 
                moves.bite, 
                moves.flamewheel, 
                moves.fireblast] 
    },
    poliwag: {
        name: "Poliwag",
        type: ["water"],
        level: 20,
        pokedexNumber: 060,
        HP: 40,
        attack: 50,
        defence: 40,
        special: 40,
        speed: 90,
        moves: [moves.watergun, 
                moves.bubble, 
                moves.hypnosis, 
                moves.doubleslap] 
    },
    poliwhirl: {
        name: "Poliwhirl",
        type: ["water"],
        level: 20,
        pokedexNumber: 061,
        HP: 65,
        attack: 65,
        defence: 65,
        special: 50,
        speed: 90,
        moves: [moves.watergun, 
                moves.bubblebeam, 
                moves.hypnosis, 
                moves.strength] 
    },
    poliwrath: {
        name: "Poliwrath",
        type: ["water", "fighting"],
        level: 20,
        pokedexNumber: 062,
        HP: 90,
        attack: 85,
        defence: 95,
        special: 70,
        speed: 70,
        moves: [moves.bubblebeam, 
                moves.strength, 
                moves.dynamicpunch, 
                moves.hypnosis] 
    },
    abra: {
        name: "Abra",
        type: ["psychic"],
        level: 20,
        pokedexNumber: 063,
        HP: 25,
        attack: 20,
        defence: 15,
        special: 105,
        speed: 90,
        moves: [moves.teleport, 
                moves.teleport, 
                moves.teleport, 
                moves.teleport] 
    },
    kadabra: {
        name: "Kadabra",
        type: ["psychic"],
        level: 20,
        pokedexNumber: 064,
        HP: 40,
        attack: 35,
        defence: 30,
        special: 120,
        speed: 105,
        moves: [moves.confusion, 
                moves.psybeam, 
                moves.psychic, 
                moves.recover] 
    },
    alakazam: {
        name: "Alakazam",
        type: ["psychic"],
        level: 20,
        pokedexNumber: 065,
        HP: 55,
        attack: 50,
        defence: 45,
        special: 135,
        speed: 120,
        moves: [moves.psychic, 
                moves.psybeam, 
                moves.recover, 
                moves.confusion] 
    },
    machop: {
        name: "Machop",
        type: ["fighting"],
        level: 20,
        pokedexNumber: 066,
        HP: 70,
        attack: 80,
        defence: 50,
        special: 35,
        speed: 35,
        moves: [moves.lowkick, 
                moves.karatechop, 
                moves.leer, 
                moves.bulkup] 
    },
    machoke: {
        name: "Machoke",
        type: ["fighting"],
        level: 20,
        pokedexNumber: 067,
        HP: 80,
        attack: 100,
        defence: 70,
        special: 50,
        speed: 45,
        moves: [moves.lowkick, 
                moves.karatechop, 
                moves.crosschop, 
                moves.bulkup] 
    },
    machamp: {
        name: "Machamp",
        type: ["fighting"],
        level: 20,
        pokedexNumber: 068,
        HP: 90,
        attack: 130,
        defence: 80,
        special: 65,
        speed: 55,
        moves: [moves.lowkick, 
                moves.dynamicpunch, 
                moves.crosschop, 
                moves.bulkup] 
    },
    bellsprout: {
        name: "Bellsprout",
        type: ["grass", "poison"],
        level: 20,
        pokedexNumber: 069,
        HP: 50,
        attack: 75,
        defence: 35,
        special: 70,
        speed: 40,
        moves: [moves.vinewhip, 
                moves.poisonpowder, 
                moves.sleeppowder, 
                moves.wrap] 
    },
    weepinbell: {
        name: "Weepinbell",
        type: ["grass", "poison"],
        level: 20,
        pokedexNumber: 070,
        HP: 65,
        attack: 90,
        defence: 50,
        special: 85,
        speed: 55,
        moves: [moves.vinewhip, 
                moves.acid, 
                moves.sleeppowder, 
                moves.wrap] 
    },
    victreebel: {
        name: "Victreebel",
        type: ["grass", "poison"],
        level: 20,
        pokedexNumber: 071,
        HP: 80,
        attack: 105,
        defence: 65,
        special: 100,
        speed: 70,
        moves: [moves.vinewhip,
                moves.acid, 
                moves.poisonpowder, 
                moves.razorleaf] 
    },
    tentacool: {
        name: "Tentacool",
        type: ["water", "poison"],
        level: 20,
        pokedexNumber: 072,
        HP: 40,
        attack: 40,
        defence: 35,
        special: 100,
        speed: 70,
        moves: [moves.poisonsting, 
                moves.acid, 
                moves.wrap, 
                moves.supersonic] 
    },
    tentacruel: {
        name: "Tentacruel",
        type: ["water", "poison"],
        level: 20,
        pokedexNumber: 073,
        HP: 80,
        attack: 70,
        defence: 65,
        special: 120,
        speed: 100,
        moves: [moves.bubblebeam, 
                moves.acid, 
                moves.wrap, 
                moves.supersonic] 
    },
    geodude: {
        name: "Geodude",
        type: ["rock", "ground"],
        level: 20,
        pokedexNumber: 074,
        HP: 40,
        attack: 80,
        defence: 100,
        special: 30,
        speed: 20,
        moves: [moves.tackle, 
                moves.defencecurl, 
                moves.rockthrow, 
                moves.harden] 
    },
    graveler: {
        name: "Graveler",
        type: ["rock", "ground"],
        level: 20,
        pokedexNumber: 075,
        HP: 55,
        attack: 95,
        defence: 115,
        special: 45,
        speed: 35,
        moves: [moves.tackle, 
                moves.defencecurl, 
                moves.rockthrow, 
                moves.selfdestruct] 
    },
    golem: {
        name: "Golem",
        type: ["rock", "ground"],
        level: 20,
        pokedexNumber: 076,
        HP: 80,
        attack: 110,
        defence: 130,
        special: 55,
        speed: 45,
        moves: [moves.earthquake, 
                moves.defencecurl, 
                moves.rockthrow, 
                moves.selfdestruct] 
    },
    ponyta: {
        name: "Ponyta",
        type: ["fire"],
        level: 20,
        pokedexNumber: 077,
        HP: 50,
        attack: 85,
        defence: 55,
        special: 65,
        speed: 90,
        moves: [moves.ember, 
                moves.flamewheel, 
                moves.stomp, 
                moves.growl] 
    },
    rapidash: {
        name: "Rapidash",
        type: ["fire"],
        level: 20,
        pokedexNumber: 078,
        HP: 65,
        attack: 100,
        defence: 70,
        special: 80,
        speed: 105,
        moves: [moves.fireblast, 
                moves.flamewheel, 
                moves.stomp, 
                moves.growl] 
    },
    slowpoke: {
        name: "Slowpoke",
        type: ["water", "psychic"],
        level: 20,
        pokedexNumber: 079,
        HP: 90,
        attack: 65,
        defence: 65,
        special: 40,
        speed: 15,
        moves: [moves.tackle, 
                moves.watergun, 
                moves.confusion, 
                moves.growl] 
    },
    slowbro: {
        name: "Slowbro",
        type: ["water", "psychic"],
        level: 20,
        pokedexNumber: 080,
        HP: 95,
        attack: 75,
        defence: 110,
        special: 80,
        speed: 30,
        moves: [moves.tackle, 
                moves.watergun, 
                moves.confusion, 
                moves.psychic] 
    },
    magnemite: {
        name: "Magnemite",
        type: ["electric"],
        level: 20,
        pokedexNumber: 081,
        HP: 25,
        attack: 35,
        defence: 70,
        special: 95,
        speed: 45,
        moves: [moves.tackle, 
                moves.sonicboom, 
                moves.thundershock, 
                moves.supersonic] 
    },
    magneton: {
        name: "Magneton",
        type: ["electric"],
        level: 20,
        pokedexNumber: 082,
        HP: 50,
        attack: 60,
        defence: 95,
        special: 120,
        speed: 70,
        moves: [moves.supersonic, 
                moves.sonicboom, 
                moves.thunderbolt, 
                moves.swift] 
    },
    farfetchd: {
        name: "Farfetch'd",
        type: ["normal", "flying"],
        level: 20,
        pokedexNumber: 083,
        HP: 52,
        attack: 65,
        defence: 55,
        special: 58,
        speed: 62,
        moves: [moves.peck, 
                moves.sandattack, 
                moves.furyattack, 
                moves.slash] 
    },
    doduo: {
        name: "Doduo",
        type: ["normal", "flying"],
        level: 20,
        pokedexNumber: 084,
        HP: 35,
        attack: 85,
        defence: 45,
        special: 35,
        speed: 75,
        moves: [moves.peck, 
                moves.quickattack, 
                moves.triattack, 
                moves.agility] 
    },
    dodrio: {
        name: "Dodrio",
        type: ["normal", "flying"],
        level: 20,
        pokedexNumber: 085,
        HP: 60,
        attack: 110,
        defence: 70,
        special: 60,
        speed: 100,
        moves: [moves.drillpeck, 
                moves.quickattack, 
                moves.triattack, 
                moves.agility] 
    },
    seel: {
        name: "Seel",
        type: ["water"],
        level: 20,
        pokedexNumber: 086,
        HP: 65,
        attack: 45,
        defence: 55,
        special: 70,
        speed: 45,
        moves: [moves.headbutt, 
                moves.growl, 
                moves.aurorabeam, 
                moves.rest] 
    },
    dewgong: {
        name: "Dewgong",
        type: ["water", "ice"],
        level: 20,
        pokedexNumber: 087,
        HP: 90,
        attack: 70,
        defence: 80,
        special: 95,
        speed: 70,
        moves: [moves.headbutt, 
                moves.blizzard, 
                moves.aurorabeam, 
                moves.rest] 
    },
    grimer: {
        name: "Grimer",
        type: ["poison"],
        level: 20,
        pokedexNumber: 088,
        HP: 80,
        attack: 80,
        defence: 50,
        special: 40,
        speed: 25,
        moves: [moves.pound, 
                moves.harden, 
                moves.sludge, 
                moves.minimize] 
    },
    muk: {
        name: "Muk",
        type: ["poison"],
        level: 20,
        pokedexNumber: 089,
        HP: 105,
        attack: 105,
        defence: 75,
        special: 65,
        speed: 50,
        moves: [moves.pound, 
                moves.harden, 
                moves.sludge, 
                moves.minimize] 
    },
    shellder: {
        name: "Shellder",
        type: ["water"],
        level: 20,
        pokedexNumber: 090,
        HP: 30,
        attack: 65,
        defence: 100,
        special: 45,
        speed: 40,
        moves: [moves.watergun, 
                moves.aurorabeam, 
                moves.tackle, 
                moves.supersonic] 
    },
    cloyster: {
        name: "Cloyster",
        type: ["water", "ice"],
        level: 20,
        pokedexNumber: 091,
        HP: 50,
        attack: 95,
        defence: 180,
        special: 85,
        speed: 70,
        moves: [moves.watergun, 
                moves.aurorabeam, 
                moves.hydropump, 
                moves.blizzard] 
    },
    gastly: {
        name: "Gastly",
        type: ["ghost", "poison"],
        level: 20,
        pokedexNumber: 092,
        HP: 30,
        attack: 35,
        defence: 30,
        special: 100,
        speed: 80,
        moves: [moves.lick, 
                moves.confuseray, 
                moves.hypnosis, 
                moves.nightshade] 
    },
    haunter: {
        name: "Haunter",
        type: ["ghost", "poison"],
        level: 20,
        pokedexNumber: 093,
        HP: 45,
        attack: 50,
        defence: 45,
        special: 115,
        speed: 95,
        moves: [moves.lick, 
                moves.confuseray, 
                moves.hypnosis, 
                moves.nightshade] 
    },
    gengar: {
        name: "Gengar",
        type: ["ghost", "poison"],
        level: 20,
        pokedexNumber: 094,
        HP: 60,
        attack: 65,
        defence: 60,
        special: 130,
        speed: 110,
        moves: [moves.lick, 
                moves.confuseray, 
                moves.hypnosis, 
                moves.dreameater] 
    },
    onix: {
        name: "Onix",
        type: ["rock", "ground"],
        level: 20,
        pokedexNumber: 095,
        HP: 35,
        attack: 45,
        defence: 160,
        special: 30,
        speed: 70,
        moves: [moves.tackle, 
                moves.harden, 
                moves.rockthrow, 
                moves.earthquake] 
    },
    drowzee: {
        name: "Drowzee",
        type: ["psychic"],
        level: 20,
        pokedexNumber: 096,
        HP: 60,
        attack: 48,
        defence: 45,
        special: 90,
        speed: 42,
        moves: [moves.hypnosis, 
                moves.confusion, 
                moves.pound, 
                moves.psybeam] 
    },
    hypno: {
        name: "Hypno",
        type: ["psychic"],
        level: 20,
        pokedexNumber: 097,
        HP: 85,
        attack: 73,
        defence: 70,
        special: 115,
        speed: 67,
        moves: [moves.hypnosis, 
                moves.psychic, 
                moves.headbutt, 
                moves.psybeam] 
    },
    krabby: {
        name: "Krabby",
        type: ["water"],
        level: 20,
        pokedexNumber: 098,
        HP: 30,
        attack: 105,
        defence: 90,
        special: 25,
        speed: 50,
        moves: [moves.bubble, 
                moves.bubblebeam, 
                moves.leer, 
                moves.vicegrip] 
    },
    kingler: {
        name: "Kingler",
        type: ["water"],
        level: 20,
        pokedexNumber: 099,
        HP: 55,
        attack: 130,
        defence: 115,
        special: 50,
        speed: 75,
        moves: [moves.bubble, 
                moves.bubblebeam, 
                moves.strength, 
                moves.vicegrip] 
    },
    voltorb: {
        name: "Voltorb",
        type: ["electric"],
        level: 20,
        pokedexNumber: 100,
        HP: 40,
        attack: 30,
        defence: 50,
        special: 55,
        speed: 100,
        moves: [moves.sonicboom, 
                moves.tackle, 
                moves.thundershock, 
                moves.swift] 
    },
    electrode: {
        name: "Electrode",
        type: ["electric"],
        level: 20,
        pokedexNumber: 101,
        HP: 60,
        attack: 50,
        defence: 70,
        special: 80,
        speed: 140,
        moves: [moves.sonicboom, 
                moves.selfdestruct, 
                moves.thundershock, 
                moves.swift] 
    },
    exeggcute: {
        name: "Exeggcute",
        type: ["grass", "psychic"],
        level: 20,
        pokedexNumber: 102,
        HP: 60,
        attack: 40,
        defence: 80,
        special: 60,
        speed: 40,
        moves: [moves.hypnosis, 
                moves.poisonpowder, 
                moves.selfdestruct, 
                moves.psybeam] 
    },
    exeggutor: {
        name: "Exeggutor",
        type: [""],
        level: 20,
        pokedexNumber: 103,
        HP: 95,
        attack: 95,
        defence: 85,
        special: 125,
        speed: 55,
        moves: [moves.hypnosis, 
                moves.stomp, 
                moves.confusion, 
                moves.psybeam] 
    },
    cubone: {
        name: "Cubone",
        type: ["ground"],
        level: 20,
        pokedexNumber: 104,
        HP: 50,
        attack: 50,
        defence: 95,
        special: 40,
        speed: 35,
        moves: [moves.growl, 
                moves.boneclub, 
                moves.bonemerang, 
                moves.headbutt] 
    },
    marowak: {
        name: "Marowak",
        type: ["ground"],
        level: 20,
        pokedexNumber: 105,
        HP: 60,
        attack: 80,
        defence: 110,
        special: 50,
        speed: 45,
        moves: [moves.strength, 
                moves.boneclub, 
                moves.bonemerang, 
                moves.headbutt] 
    },
    hitmonlee: {
        name: "Hitmonlee",
        type: ["fighting"],
        level: 20,
        pokedexNumber: 106,
        HP: 50,
        attack: 120,
        defence: 53,
        special: 35,
        speed: 87,
        moves: [moves.doublekick, 
                moves.lowkick,  
                moves.hijumpkick, 
                moves.focusenergy] 
    },
    hitmonpunch: {
        name: "Hitmonpunch",
        type: ["fighting"],
        level: 20,
        pokedexNumber: 107,
        HP: 50,
        attack: 105,
        defence: 79,
        special: 35,
        speed: 76,
        moves: [moves.doubleslap, 
                moves.agility, 
                moves.megapunch, 
                moves.dynamicpunch] 
    },
    lickitung: {
        name: "Lickitung",
        type: ["normal"],
        level: 20,
        pokedexNumber: 108,
        HP: 90,
        attack: 55,
        defence: 75,
        special: 60,
        speed: 30,
        moves: [moves.lick, 
                moves.wrap, 
                moves.stomp, 
                moves.supersonic] 
    },
    koffing: {
        name: "Koffing",
        type: ["poison"],
        level: 20,
        pokedexNumber: 109,
        HP: 40,
        attack: 65,
        defence: 95,
        special: 60,
        speed: 35,
        moves: [moves.tackle, 
                moves.smog, 
                moves.sludge, 
                moves.selfdestruct] 
    },
    weezing: {
        name: "Weezing",
        type: ["poison"],
        level: 20,
        pokedexNumber: 110,
        HP: 65,
        attack: 90,
        defence: 120,
        special: 85,
        speed: 60,
        moves: [moves.tackle, 
                moves.smog, 
                moves.sludge, 
                moves.selfdestruct] 
    },
    rhyhorn: {
        name: "Rhyhorn",
        type: ["ground", "rock"],
        level: 20,
        pokedexNumber: 111,
        HP: 80,
        attack: 85,
        defence: 95,
        special: 30,
        speed: 25,
        moves: [moves.stomp, 
                moves.furyattack, 
                moves.leer, 
                moves.bodyslam] 
    },
    rhydon: {
        name: "Rhydon",
        type: ["ground", "rock"],
        level: 20,
        pokedexNumber: 112,
        HP: 105,
        attack: 130,
        defence: 120,
        special: 45,
        speed: 40,
        moves: [moves.stomp, 
                moves.furyattack, 
                moves.earthquake, 
                moves.bodyslam] 
    },
    chansey: {
        name: "Chansey",
        type: ["normal"],
        level: 20,
        pokedexNumber: 113,
        HP: 250,
        attack: 5,
        defence: 5,
        special: 105,
        speed: 50,
        moves: [moves.doubleslap, 
                moves.sing, 
                moves.growl, 
                moves.pound] 
    },
    tangela: {
        name: "Tangela",
        type: ["grass"],
        level: 20,
        pokedexNumber: 114,
        HP: 65,
        attack: 55,
        defence: 115,
        special: 100,
        speed: 60,
        moves: [moves.vinewhip, 
                moves.absorb, 
                moves.wrap, 
                moves.poisonpowder] 
    },
    kangaskhan: {
        name: "Kangaskhan",
        type: ["normal"],
        level: 20,
        pokedexNumber: 115,
        HP: 105,
        attack: 95,
        defence: 80,
        special: 60,
        speed: 90,
        moves: [moves.bite, 
                moves.tailwhip, 
                moves.bodyslam, 
                moves.earthquake] 
    },
    horsea: {
        name: "Horsea",
        type: ["water"],
        level: 20,
        pokedexNumber: 116,
        HP: 30,
        attack: 40,
        defence: 70,
        special: 70,
        speed: 60,
        moves: [moves.bubble, 
                moves.watergun, 
                moves.leer, 
                moves.agility] 
    },
    seadra: {
        name: "Seadra",
        type: ["water"],
        level: 20,
        pokedexNumber: 117,
        HP: 55,
        attack: 65,
        defence: 95,
        special: 95,
        speed: 85,
        moves: [moves.hydropump, 
                moves.watergun, 
                moves.agility, 
                moves.surf] 
    },
    goldeen: {
        name: "Goldeen",
        type: ["water"],
        level: 20,
        pokedexNumber: 118,
        HP: 45,
        attack: 67,
        defence: 60,
        special: 50,
        speed: 63,
        moves: [moves.peck, 
                moves.watergun, 
                moves.supersonic, 
                moves.furyattack] 
    },
    seaking: {
        name: "Seaking",
        type: ["water"],
        level: 20,
        pokedexNumber: 119,
        HP: 80,
        attack: 92,
        defence: 65,
        special: 80,
        speed: 68,
        moves: [moves.waterfall, 
                moves.watergun, 
                moves.supersonic, 
                moves.furyattack] 
    },
    staryu: {
        name: "Staryu",
        type: ["water"],
        level: 20,
        pokedexNumber: 120,
        HP: 30,
        attack: 45,
        defence: 55,
        special: 70,
        speed: 85,
        moves: [moves.tackle, 
                moves.watergun, 
                moves.harden, 
                moves.swift] 
    },
    starmie: {
        name: "Starmie",
        type: ["water", "psychic"],
        level: 20,
        pokedexNumber: 121,
        HP: 60,
        attack: 75,
        defence: 85,
        special: 100,
        speed: 115,
        moves: [moves.hydropump, 
                moves.watergun, 
                moves.harden, 
                moves.swift] 
    },
    mrmime: {
        name: "Mr Mime",
        type: ["psychic"],
        level: 20,
        pokedexNumber: 122,
        HP: 40,
        attack: 45,
        defence: 64,
        special: 100,
        speed: 90,
        moves: [moves.confusion, 
                moves.doubleslap, 
                moves.psychic, 
                moves.bodyslam] 
    },
    scyther: {
        name: "Scyther",
        type: ["bug", "flying"],
        level: 20,
        pokedexNumber: 123,
        HP: 70,
        attack: 110,
        defence: 80,
        special: 55,
        speed: 105,
        moves: [moves.quickattack, 
                moves.slash, 
                moves.agility, 
                moves.wingattack] 
    },
    jynx: {
        name: "Jynx",
        type: ["ice", "psychic"],
        level: 20,
        pokedexNumber: 124,
        HP: 65,
        attack: 50,
        defence: 35,
        special: 100,
        speed: 95,
        moves: [moves.pound, 
                moves.lick, 
                moves.doubleslap, 
                moves.blizzard] 
    },
    electabuzz: {
        name: "Electabuzz",
        type: ["electric"],
        level: 20,
        pokedexNumber: 125,
        HP: 65,
        attack: 83,
        defence: 57,
        special: 90,
        speed: 105,
        moves: [moves.quickattack, 
                moves.leer, 
                moves.thundershock, 
                moves.thunder] 
    },
    magmar: {
        name: "Magmar",
        type: ["fire"],
        level: 20,
        pokedexNumber: 126,
        HP: 65,
        attack: 95,
        defence: 57,
        special: 90,
        speed: 93,
        moves: [moves.ember, 
                moves.leechlife, 
                moves.flamethrower, 
                moves.smog] 
    },
    pinsir: {
        name: "Pinsir",
        type: ["bug"],
        level: 20,
        pokedexNumber: 127,
        HP: 65,
        attack: 125,
        defence: 100,
        special: 55,
        speed: 85,
        moves: [moves.vicegrip, 
                moves.harden, 
                moves.slash, 
                moves.strength] 
    },
    tauros: {
        name: "Tauros",
        type: ["normal"],
        level: 20,
        pokedexNumber: 128,
        HP: 75,
        attack: 100,
        defence: 95,
        special: 70,
        speed: 110,
        moves: [moves.tackle, 
                moves.stomp, 
                moves.leer, 
                moves.bodyslam] 
    },
    magikarp: {
        name: "Magikarp",
        type: ["water"],
        level: 20,
        pokedexNumber: 129,
        HP: 20,
        attack: 10,
        defence: 55,
        special: 15,
        speed: 80,
        moves: [moves.splash, 
                moves.splash, 
                moves.splash, 
                moves.splash] 
    },
    gyarados: {
        name: "Gyarados",
        type: ["water", "flying"],
        level: 20,
        pokedexNumber: 130,
        HP: 95,
        attack: 125,
        defence: 79,
        special: 100,
        speed: 81,
        moves: [moves.bite, 
                moves.dragonrage, 
                moves.leer, 
                moves.hydropump] 
    },
    lapras: {
        name: "Lapras",
        type: ["water", "ice"],
        level: 20,
        pokedexNumber: 131,
        HP: 130,
        attack: 85,
        defence: 80,
        special: 95,
        speed: 60,
        moves: [moves.watergun, 
                moves.sing, 
                moves.aurorabeam, 
                moves.surf] 
    },
    ditto: {
        name: "Ditto",
        type: ["normal"],
        level: 20,
        pokedexNumber: 132,
        HP: 48,
        attack: 48,
        defence: 48,
        special: 48,
        speed: 48,
        moves: [moves.transform, 
                moves.transform, 
                moves.transform, 
                moves.transform] 
    },
    eevee: {
        name: "Eevee",
        type: ["normal"],
        level: 20,
        pokedexNumber: 133,
        HP: 55,
        attack: 55,
        defence: 50,
        special: 65,
        speed: 55,
        moves: [moves.tackle, 
                moves.tailwhip, 
                moves.bite, 
                moves.quickattack] 
    },
    vaporeon: {
        name: "Vaporeon",
        type: ["water"],
        level: 20,
        pokedexNumber: 134,
        HP: 130,
        attack: 65,
        defence: 60,
        special: 110,
        speed: 65,
        moves: [moves.watergun, 
                moves.quickattack, 
                moves.bite, 
                moves.surf] 
    },
    jolteon: {
        name: "Jolteon",
        type: ["electric"],
        level: 20,
        pokedexNumber: 135,
        HP: 65,
        attack: 65,
        defence: 60,
        special: 110,
        speed: 130,
        moves: [moves.quickattack, 
                moves.thundershock, 
                moves.doublekick, 
                moves.thunder] 
    },
    flareon: {
        name: "Flareon",
        type: ["fire"],
        level: 20,
        pokedexNumber: 136,
        HP: 65,
        attack: 130,
        defence: 60,
        special: 110,
        speed: 65,
        moves: [moves.quickattack, 
                moves.ember, 
                moves.bite, 
                moves.flamethrower] 
    },
    porygon: {
        name: "Porygon",
        type: ["normal"],
        level: 20,
        pokedexNumber: 137,
        HP: 65,
        attack: 60,
        defence: 70,
        special: 75,
        speed: 40,
        moves: [moves.tackle, 
                moves.psybeam, 
                moves.recover, 
                moves.triattack] 
    },
    omanyte: {
        name: "Omanyte",
        type: ["rock", "water"],
        level: 20,
        pokedexNumber: 138,
        HP: 35,
        attack: 40,
        defence: 100,
        special: 90,
        speed: 35,
        moves: [moves.watergun, 
                moves.leer, 
                moves.rockthrow, 
                moves.bodyslam] 
    },
    omastar: {
        name: "Omastar",
        type: ["rock", "water"],
        level: 20,
        pokedexNumber: 139,
        HP: 70,
        attack: 60,
        defence: 125,
        special: 115,
        speed: 55,
        moves: [moves.watergun, 
                moves.hydropump, 
                moves.rockthrow, 
                moves.bodyslam] 
    },
    kabuto: {
        name: "Kabuto",
        type: ["rock", "water"],
        level: 20,
        pokedexNumber: 140,
        HP: 30,
        attack: 80,
        defence: 90,
        special: 45,
        speed: 55,
        moves: [moves.scratch, 
                moves.harden, 
                moves.absorb, 
                moves.leer] 
    },
    kabutops: {
        name: "Kabutops",
        type: ["rock", "water"],
        level: 20,
        pokedexNumber: 141,
        HP: 60,
        attack: 115,
        defence: 105,
        special: 70,
        speed: 80,
        moves: [moves.scratch, 
                moves.harden, 
                moves.slash, 
                moves.absorb] 
    },
    aerodactyl: {
        name: "Aerodactyl",
        type: ["rock", "flying"],
        level: 20,
        pokedexNumber: 142,
        HP: 80,
        attack: 105,
        defence: 65,
        special: 60,
        speed: 130,
        moves: [moves.wingattack, 
                moves.agility, 
                moves.bite, 
                moves.rockthrow] 
    },
    snorlax: {
        name: "Snorlax",
        type: ["normal"],
        level: 20,
        pokedexNumber: 143,
        HP: 160,
        attack: 110,
        defence: 65,
        special: 65,
        speed: 30,
        moves: [moves.headbutt, 
                moves.rest, 
                moves.bodyslam, 
                moves.harden] 
    },
    articuno: {
        name: "Articuno",
        type: ["ice", "flying"],
        level: 20,
        pokedexNumber: 144,
        HP: 90,
        attack: 85,
        defence: 100,
        special: 125,
        speed: 85,
        moves: [moves.blizzard, 
                moves.peck, 
                moves.agility, 
                moves.aurorabeam] //skal egentlig være icebeam, skifter senere
    },
    zapdos: {
        name: "Zapdos",
        type: ["electric", "flying"],
        level: 20,
        pokedexNumber: 145,
        HP: 90,
        attack: 90,
        defence: 85,
        special: 125,
        speed: 100,
        moves: [moves.thundershock, 
                moves.thunder, 
                moves.drillpeck, 
                moves.agility] 
    },
    moltres: {
        name: "Moltres",
        type: ["fire", "flying"],
        level: 20,
        pokedexNumber: 146,
        HP: 90,
        attack: 100,
        defence: 90,
        special: 125,
        speed: 90,
        moves: [moves.peck, 
                moves.flamethrower, 
                moves.agility, 
                moves.fly] 
    },
    dratini: {
        name: "Dratini",
        type: ["dragon"],
        level: 20,
        pokedexNumber: 147,
        HP: 41,
        attack: 64,
        defence: 45,
        special: 50,
        speed: 50,
        moves: [moves.wrap, 
                moves.leer, 
                moves.thunderwave, 
                moves.dragonrage] 
    },
    dragonair: {
        name: "Dragonair",
        type: ["dragon"],
        level: 20,
        pokedexNumber: 148,
        HP: 61,
        attack: 84,
        defence: 65,
        special: 70,
        speed: 70,
        moves: [moves.wrap, 
                moves.agility, 
                moves.thunderwave, 
                moves.dragonrage] 
    },
    dragonite: {
        name: "Dragonite",
        type: ["dragon", "flying"],
        level: 20,
        pokedexNumber: 149,
        HP: 91,
        attack: 134,
        defence: 95,
        special: 100,
        speed: 80,
        moves: [moves.wingattack, 
                moves.slash, 
                moves.hyperbeam, 
                moves.dragonrage] 
    },
    mewtwo: {
        name: "Mewtwo",
        type: ["psychic"],
        level: 20,
        pokedexNumber: 150,
        HP: 106,
        attack: 110,
        defence: 90,
        special: 154,
        speed: 130,
        moves: [moves.psychic, 
                moves.recover, 
                moves.swift, 
                moves.confusion] 
    },
    mew: {
        name: "Mew",
        type: ["psychic"],
        level: 20,
        pokedexNumber: 151,
        HP: 100,
        attack: 100,
        defence: 100,
        special: 100,
        speed: 100,
        moves: [moves.pound, 
                moves.transform, 
                moves.metronome, 
                moves.psychic] 
    },
};
/****** MAL FOR POKEMON ******
x: {
        name: "",
        type: [""],
        level: 20,
        pokedexNumber: ,
        HP: ,
        attack: ,
        defence: ,
        special: ,
        speed: ,
        moves: [moves., 
                moves., 
                moves., 
                moves.] 
    },
********************************/
var pokedexID = [pokedex.bulbasaur, 
                 pokedex.ivysaur,
                 pokedex.venusaur,
                 pokedex.charmander,
                 pokedex.charmeleon,
                 pokedex.charizard,
                 pokedex.squirtle,
                 pokedex.wartortle,
                 pokedex.blastoise, 
                 pokedex.caterpie,
                 pokedex.metapod,
                 pokedex.butterfree,
                 pokedex.weedle,
                 pokedex.kakuna, 
                 pokedex.beedrill, 
                 pokedex.pidgey,
                 pokedex.pidgeotto,
                 pokedex.pidgeot,
                 pokedex.rattata, 
                 pokedex.raticate, 
                 pokedex.spearow, 
                 pokedex.ekans, 
                 pokedex.arbok, 
                 pokedex.pikachu,
                 pokedex.raichu, 
                 pokedex.sandshrew,
                 pokedex.sandslash, 
                 pokedex.nidoranF, 
                 pokedex.nidorina, 
                 pokedex.nidoqueen, 
                 pokedex.nidoranM, 
                 pokedex.nidorino,
                 pokedex.nidoking, 
                 pokedex.clefairy, 
                 pokedex.clefable, 
                 pokedex.vulpix, 
                 pokedex.ninetales, 
                 pokedex.jigglypuff, 
                 pokedex.wigglytuff, 
                 pokedex.zubat, 
                 pokedex.golbat, 
                 pokedex.oddish, 
                 pokedex.gloom, 
                 pokedex.vileplume, 
                 pokedex.paras, 
                 pokedex.parasect, 
                 pokedex.venonat, 
                 pokedex.venomoth, 
                 pokedex.diglett, 
                 pokedex.dugtrio, 
                 pokedex.meowth, 
                 pokedex.persian, 
                 pokedex.psyduck, 
                 pokedex.golduck, 
                 pokedex.mankey, 
                 pokedex.primeApe, 
                 pokedex.growlithe, 
                 pokedex.arcanine, 
                 pokedex.poliwag, 
                 pokedex.poliwhirl, 
                 pokedex.poliwrath, 
                 pokedex.abra, 
                 pokedex.kadabra, 
                 pokedex.alakazam, 
                 pokedex.machop, 
                 pokedex.machoke, 
                 pokedex.machamp, 
                 pokedex.bellsprout, 
                 pokedex.weepinbell, 
                 pokedex.victreebel, 
                 pokedex.tentacool, 
                 pokedex.tentacruel, 
                 pokedex.geodude, 
                 pokedex.graveler, 
                 pokedex.golem, 
                 pokedex.ponyta, 
                 pokedex.rapidash, 
                 pokedex.slowpoke, 
                 pokedex.slowbro, 
                 pokedex.magnemite, 
                 pokedex.magneton, 
                 pokedex.farfetchd, 
                 pokedex.doduo, 
                 pokedex.dodrio, 
                 pokedex.seel, 
                 pokedex.dewgong, 
                 pokedex.grimer, 
                 pokedex.muk, 
                 pokedex.shellder, 
                 pokedex.cloyster, 
                 pokedex.gastly, 
                 pokedex.haunter, 
                 pokedex.gengar, 
                 pokedex.onix, 
                 pokedex.drowzee, 
                 pokedex.hypno, 
                 pokedex.krabby, 
                 pokedex.kingler, 
                 pokedex.voltorb, 
                 pokedex.electrode, 
                 pokedex.exeggcute, 
                 pokedex.exeggutor, 
                 pokedex.cubone, 
                 pokedex.marowak, 
                 pokedex.hitmonlee, 
                 pokedex.hitmonpunch, 
                 pokedex.lickitung, 
                 pokedex.koffing, 
                 pokedex.weezing, 
                 pokedex.rhyhorn, 
                 pokedex.rhydon, 
                 pokedex.chansey, 
                 pokedex.tangela, 
                 pokedex.kangaskhan, 
                 pokedex.horsea, 
                 pokedex.seadra, 
                 pokedex.goldeen, 
                 pokedex.seaking, 
                 pokedex.staryu, 
                 pokedex.starmie, 
                 pokedex.mrmime, 
                 pokedex.scyther, 
                 pokedex.jynx, 
                 pokedex.electabuzz, 
                 pokedex.magmar, 
                 pokedex.pinsir, 
                 pokedex.tauros, 
                 pokedex.magikarp, 
                 pokedex.gyarados, 
                 pokedex.lapras, 
                 pokedex.ditto, 
                 pokedex.eevee, 
                 pokedex.vaporeon, 
                 pokedex.jolteon, 
                 pokedex.flareon, 
                 pokedex.porygon, 
                 pokedex.omanyte, 
                 pokedex.omastar, 
                 pokedex.kabuto, 
                 pokedex.kabutops, 
                 pokedex.aerodactyl, 
                 pokedex.snorlax, 
                 pokedex.articuno, 
                 pokedex.zapdos, 
                 pokedex.moltres, 
                 pokedex.dratini, 
                 pokedex.dragonair, 
                 pokedex.dragonite, 
                 pokedex.mewtwo, 
                 pokedex.mew
                ];